export const quotes = [
  "The only way to do great work is to love what you do",
  "Don't watch the clock; do what it does. Keep going.",
  "The secret of getting ahead is getting started.",
  "Believe you can and you're halfway there.",
  "Feeling burnt out? Take a break and go for a walk outside.",
  "Succeeding requires iterations. Remember, Rome wasn't built in a day.",
  "You don't have to see the whole staircase, just take the first step.",
  "Don't wait. The time will never be just right.",
  "If at first, you don't succeed, skydiving is not for you.",
  "Feeling lost? Take a deep breath.",
  "Random quote generator go brr.",
  "Don't look back. March forward",
  "Being a functional adult everyday seems a bit -excessive-.",
  "If you think you are too small to make a difference, try sleeping with a mosquito.",
  "Go easy on yourself. Whatever you do today, let it be enough",
  "Listen to your gut feelings.",
  "You can",
  "Life is not a race. It's a marathon. Pace yourself accordingly.",
  "Love, laugh, live.",
  "Sleeping on my keyboard. If I answer, I am talking in my sleep. Goodnight.",
  "Six month vacations twice a year.",
  // Add more motivational quotes as needed
];
